// Generated by Selenium IDE
package welcome;


import org.junit.jupiter.api.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class Test1 {
    private  WebDriver driver;
    @BeforeEach
    public void setUp() {
        driver = new FirefoxDriver();
        FirefoxOptions ffOptions = new FirefoxOptions();
        driver = new FirefoxDriver(ffOptions);
        driver.manage().window().maximize();
        }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void test1() {
        driver.get("http://fmi-schedule.chnu.edu.ua/schedule?semester=55");
//        driver.manage().window().setSize(new Dimension(1254, 823));
        driver.findElement(By.xpath("xpath=//div[@id='root']/div/section/section/div/form/div[3]/div/div/div/input")).click();
        driver.findElement(By.id("mui-11178-option-1")).click();
        driver.findElement(By.cssSelector(".schedule-form_submit")).click();
        driver.findElement(By.cssSelector("h1")).click();
        driver.findElement(By.cssSelector("h1")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("h1"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
    }
}
